name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: dong002/kbexam
          stage: main
          yaml: |
            name: kb-backend
            app: node@21
            options:
              env:
                - name: NODE_ENV
                  value: production
                - name: DB_PASSWD
                  value: zpdlqlrnralsdmsgod
                - name: DB_HOST
                  value: svc.sel5.cloudtype.app
                - name: DB_PORT
                  value: "30055"
                - name: DB_USER
                  value: root
                - name: DB_DATABASE
                  value: kb
              ports: 3000
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}